name: Nightly SideStore build
on:
  push:
    branches:
      - develop

jobs:
  build:
    name: Build and upload SideStore Nightly
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: 'macos-12'
            version: '14.2'

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install dependencies
        run: brew install ldid

      - name: Cache .nightly-build-num
        uses: actions/cache@v3
        with:
          path: .nightly-build-num
          key: nightly-build-num

      - name: Increase nightly build number and set as version
        run: bash .github/workflows/increase-nightly-build-num.sh

      - name: Get version
        id: version
        run: echo "version=$(grep MARKETING_VERSION Build.xcconfig | sed -e "s/MARKETING_VERSION = //g")" >> $GITHUB_OUTPUT

      - name: Echo version
        run: echo "${{ steps.version.outputs.version }}"

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1.4.1
        with:
          xcode-version: ${{ matrix.version }}

      - name: Build SideStore
        run: make build | xcpretty && exit ${PIPESTATUS[0]}

      - name: Fakesign app
        run: make fakesign

      - name: Convert to IPA
        run: make ipa
          
      - name: Get current date
        id: date
        run: echo "date=$(date -u +'%c')" >> $GITHUB_OUTPUT

      - name: Get current date in AltStore date form
        id: date_altstore
        run: echo "date=$(date -u +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Add version to IPA file name
        run: mv SideStore.ipa SideStore-test.ipa

      - name: Upload SideStore.ipa Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: SideStore-test.ipa
          path: SideStore-test.ipa

      - name: Upload *.dSYM Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: SideStore-test-dSYM
          path: ./*.dSYM/

      # - name: Reset cache for apps.sidestore.io/nightly
      #   run: sleep 10 && curl https://apps.sidestore.io/reset-cache/nightly/${{ secrets.SIDESOURCE_KEY }}
